baseURL = 'https://cameronknox.io/'
languageCode = 'en-us'
title = 'Camerons Blog'
theme = 'archie'
copyright = "Â© CameronKnox"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/CameronKnox"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4