baseURL = 'https://cameronknox.io/'
languageCode = 'en-us'
title = 'Camerons Blog'
copyright = "Â© CameronKnox"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    codeFences = true
    guessSyntax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/CameronKnox"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3